# Docker Compose project name
name: studyhub

services:
  studyhub_web:
    build:
      context: ./study-hub
      dockerfile: Dockerfile
      target: production
    image: studyhub_web:production
    container_name: studyhub-web-production
    restart: always
    env_file:
      - .env/.production.django.env
    ports:
      - 8888:8000
    networks:
      - studyhub

networks:
  studyhub:
    name: studyhub
    external: true
