# Docker Compose project name
name: studyhub

services:
  studyhub_web:
    build:
      context: ./study-hub
      dockerfile: Dockerfile
      target: local
    image: studyhub_web:local
    container_name: studyhub-web-local
    restart: always
    env_file:
      - .env/.local.django.env
    ports:
      - 8888:8000
    volumes:
      - ./study-hub:/usr/src
    networks:
      - studyhub

networks:
  studyhub:
    name: studyhub
    external: true
